### ISSUE TITLE
'CGrid_geo' object has no attribute 'Vtransform'

### ISSUE THREAD

**Issue by ghost** [kthyng/tracpy#13]
Good day.

The above-mentioned error happened shortly after running this code line (from notebook manual) :

lonp, latp, zp, t, T0, U, V = tracpy.run.run(tp, date, lon0, lat0)

error:  'CGrid_geo' object has no attribute 'Vtransform'

**Comment by kthyng** [comment]
Hi @TKzee2027! Unfortunately I'm not developing this package anymore. I would suggest you look into [ocean parcels](https://oceanparcels.org/) as an actively-developing package.

**Comment by ghost** [comment]
Hi Kristen

Thank you for getting back to me.

I would certainly explore the ocean parcels.

With kind regards
TK

**Comment by ChrisBarker-NOAA** [comment]
NOTE: 

Parcels is pretty cool, but there are other options as well. Depending on your use case,  PyGNOME may be a good option:

https://github.com/NOAA-ORR-ERD/PyGnome

Don't be distracted by all the oil spill stuff -- at its core it's a particle tracker that supports a wide variety of ocean model grids. 

And it's a framework for adding arbitrary attributes and process to the particles, which can be used for a variety of purposes other than oil :-)

**Comment by ghost** [comment]
Thank you so much, Chris.

I will explore the PyGnome too - heard about it last night at the
Copernicus MarineData4America workshop.

Once again, many thanks.

Tshikana

**Comment by kthyng** [comment]
Thanks @ChrisBarker-NOAA — good recommendation.
