### ISSUE TITLE
Are there any available links to acquire in sample data of 'manual' code?

### ISSUE THREAD

**Issue by frong0824** [kthyng/tracpy#15]
# Location of TXLA model output file and grid, on a thredds server.
loc = ’http://barataria.tamu.edu:8080/thredds/dodsC/NcML/txla_nesting6.nc’

**Comment by kthyng** [comment]
Hi @frong0824. The same or similar model output can now be found at either 
url = 'https://gcoos5.geos.tamu.edu/thredds/dodsC/NcML/nowcast_agg.nc'
or 
url = 'http://barataria.geos.tamu.edu/thredds/dodsC/NcML/forecast_his_archive_agg.nc'

However, please note that I'm not developing tracpy anymore, so you'd probably be better off trying out a different particle tracking code. Other options include OpenDrift, Parcels (or ocean parcels), and PyGnome.

**Comment by frong0824** [comment]
Thank you so much.
